package io.github.Plants_Vs_Zombies_2.network.protocol;

public enum ProtocolErrorCode {
    INVALID_JSON,
    MALFORMED_MESSAGE,
    UNSUPPORTED_MESSAGE_TYPE,
    UNSUPPORTED_PROTOCOL_VERSION,
    HANDSHAKE_REQUIRED,
    HELLO_ALREADY_COMPLETED,
    MALFORMED_PAYLOAD,
    VALIDATION_FAILED,
    USERNAME_EXISTS,
    INVALID_CREDENTIALS,
    ALREADY_AUTHENTICATED,
    AUTH_REQUIRED,
    USER_ALREADY_ONLINE,
    INTERNAL_SERVER_ERROR,
    UNEXPECTED_RESPONSE
}
