package io.github.Plants_Vs_Zombies_2.model.quest;

/** Machine-readable conditions for the nineteen phase-one quests. */
public enum QuestCondition {
    COLLECT_SUN,
    KILL_ZOMBIES_IN_CHAPTER,
    KILL_ONLY_WITH_PLANT,
    KILL_ONLY_WITH_CACTUS,
    WIN_WITH_MAXIMUM_PLANT_LOSSES,
    FINISH_WITH_ZERO_SUN,
    KILL_TEN_WITHIN_THIRTY_SECONDS,
    USE_THREE_EXPLOSIVE_PLANTS,
    FINISH_WITH_SYMMETRICAL_GARDEN,
    KILL_ONLY_WITH_FAMILY,
    WIN_WITHOUT_FAMILY,
    WIN_DAY_LEVEL_WITH_SHROOMS,
    WIN_FIVE_AT_MAXIMUM_DIFFICULTY,
    KILL_IN_FIRST_COLUMN_WITHOUT_MOWER,
    FINISH_WITHOUT_GARDEN_SYMMETRY,
    WIN_WITH_EXACTLY_THREE_SUN_PRODUCERS,
    WIN_WITH_EMPTY_COLUMN,
    WIN_WITH_EMPTY_ROW,
    WIN_WITH_EMPTY_CROSS
}
