[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  api "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  api "com.github.raeleus.TenPatch:tenpatch:$tenPatchVersion"

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}

jar {
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

task runConsole(type: JavaExec) {
    mainClass = 'io.github.some_example_name.ConsoleLauncher'
    classpath = sourceSets.main.runtimeClasspath
    standardInput = System.in
}

